name: Infra Workflow

on: 
  push:
    branches:
      - main
      - feature/**
jobs:
  job1:
    name: first job
    runs-on: sheetalrunner
    steps:
      - name: myfirst step
        run: this is the first step
 
